### ISSUE TITLE
IntMap.insert unexpected behaviour

### ISSUE THREAD

**Issue by clinuxrulz** [tel/purescript-intmaps#6]
When we use IntMap.insert on a key that already exists in the IntMap, I would of expected the value at the key to be replaced by the new value, but instead it was retained.

If this is a bug I think the following

```
insert :: forall a . Int -> a -> IntMap a -> IntMap a
insert = insertWithKey (\_ a _ -> a) 
```

Needs to be changed to

```
insert :: forall a . Int -> a -> IntMap a -> IntMap a
insert = insertWithKey (\_ _ a -> a) 
```

**Comment by tel** [comment]
Beautiful, thanks.

**Comment by tel** [comment]
That is the fix—I miswrote it because I was thinking "second argument" and forgot the "key" argument.
